###
POST http://localhost:3080/api/documents/add HTTP/1.1
Content-Type: application/json

{
    "owner": "nomote8754@vootin.com",
    "frontPage": {
        "documentTitle": "Roy Juego 2",
        "documentLogo": "https://inaturalist-open-data.s3.amazonaws.com/photos/75868387/large.jpg",
        "companyName": "Roy Games",
        "companyLogo": "https://inaturalist-open-data.s3.amazonaws.com/photos/75868387/large.jpg",
        "collaborators": ["Roy", "Fabri", "Eli"],
        "lastUpdated": "Sat Mar 07 2023 10:26:45 GMT-0600"
    },
    "documentContent": [{
        "sectionTitle": "Titulo Uno3",
        "content": {
            "selfContent": "markdown",
            "subSections": [{
                "subSectionTitle": "Subtitulo Uno3",
                "subSectionContent": {}
            }]
        }
    }]
}

###
GET http://localhost:3080/api/documents/get HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/get/640a5e66d315c056fd32867f HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/getInfo/640a5e66d315c056fd32867f HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3080/api/documents/update/640a5e66d315c056fd32867f HTTP/1.1
Content-Type: application/json

{
    "frontPage": {
        "documentTitle": "El juego de la muerte",
        "documentLogo": "https://brandemia.org/contenido/subidas/2016/11/cabecera_nesquik2-960x640.jpg",
        "companyName": "OG Games",
        "companyLogo": "https://brandemia.org/contenido/subidas/2016/11/cabecera_nesquik2-960x640.jpg",
        "collaborators": ["Abiel", "Juzo", "Pablo", "Gonzalo", "Julio"],
        "lastUpdated": "Sat Feb 02 2023 11:26:45 GMT-0600"
    }
}

###
DELETE http://localhost:3080/api/documents/delete/640a5f04d315c056fd328683 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/getInfoByOwner/abielpg.juzo@gmail.com HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3080/api/documents/getInfoShared HTTP/1.1
Content-Type: application/json

[
    "640a5fd3d315c056fd328687",
    "640a5ffbd315c056fd32868b"
]

###
PUT http://localhost:3080/api/documents/updateOwner/nomote8754@vootin.com HTTP/1.1
Content-Type: application/json

{
    "owner": "yoseleh299@maazios.com"
}