###
POST http://localhost:3080/api/documents/add HTTP/1.1
Content-Type: application/json

{
    "owner": "ab@gmail.com",
    "frontPage": {
        "documentTitle": "Titulo Documento",
        "documentLogo": "https://www.freeiconspng.com/uploads/no-image-icon-11.PNG",
        "companyName": "Nombre Desarrolladora",
        "companyLogo": "https://www.freeiconspng.com/uploads/no-image-icon-11.PNG",
        "collaborators": ["Abi1", "Abi2"],
        "lastUpdated": "Sat Mar 07 2023 10:26:45 GMT-0600"
    },
    "documentContent": [{
        "sectionTitle": "Titulo Seccion",
        "subSections": [{
            "subSectionTitle": "Titulo Subseccion",
            "subSectionContent": {}
        }]
    }]
}

###
GET http://localhost:3080/api/documents/get HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/get/641b1c93ba799a52b5aac610 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/getInfo/641b1c93ba799a52b5aac610 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3080/api/documents/update/641b1c93ba799a52b5aac610 HTTP/1.1
Content-Type: application/json

{
    "frontPage": {
        "documentTitle": "Titulo Documento Nuevo",
        "documentLogo": "https://www.freeiconspng.com/uploads/no-image-icon-11.PNG",
        "companyName": "Nombre Desarrolladora Nuevo",
        "companyLogo": "https://www.freeiconspng.com/uploads/no-image-icon-11.PNG",
        "collaborators": ["Abi1", "Abi2", "Abi3"],
        "lastUpdated": "Sat Mar 08 2023 10:26:45 GMT-0600"
    }
}

###
DELETE http://localhost:3080/api/documents/delete/641b1c93ba799a52b5aac610 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/documents/getInfoByOwner/ab@gmail.com HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3080/api/documents/getInfoShared HTTP/1.1
Content-Type: application/json

[
    "640a5fd3d315c056fd328687",
    "640a5ffbd315c056fd32868b"
]

###
PUT http://localhost:3080/api/documents/updateOwner/ab@gmail.com HTTP/1.1
Content-Type: application/json

{
    "owner": "ab2@gmail.com"
}

###
PUT http://localhost:3080/api/documents/updateOnlySubSectionByIds/640f6502caf1011d0b97573d/640f6502caf1011d0b975743/640f6502caf1011d0b975744 HTTP/1.1
Content-Type: application/json

{
    "platforms": [
        "Windows",
        "Playstation",
        "Nintento2"
    ]
}

###
PUT http://localhost:3080/api/documents/updateOnlySubSectionByTitles/640f6502caf1011d0b97573d/Technical Information/Tech HTTP/1.1
Content-Type: application/json

{
    "platforms": [
        "Windows",
        "Playstation",
        "Nintento3"
    ]
}