###
GET http://localhost:3080/api/users/get HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/users/get/mofixac660@vootin.com HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3080/api/users/delete/kalale8462@pubpng.com HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3080/api/users/sendCode/lanzerth13@gmail.com HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/users/login/poyohoh755@v2ssr.com/5L0hZSKZt HTTP/1.1
Content-Type: application/json
