name: Build, Deploy, Serve
on: [push]
jobs:

  buildDep:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Running first set of commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd proyecto/GDD-Maker
          git stash
          git pull
          cd Backend
          sudo npm i
          cd src
          if [ -d frontendBuild ]; then rm -r frontendBuild; fi
          echo "DELETING OLD FRONTEND BUILD"
          cd ../../Frontend
          sudo npm i
          echo "UPDATING FRONTEND DEPENDENCIES"
          ng build
          echo "NEW APP BUILT"
          mv frontendBuild ../Backend/src/frontendBuild
          echo "MOVING"  
          echo "APP UPDATED"
          
  serve:
    name: Serve
    runs-on: ubuntu-latest
    
    steps:
    - name: Running second set of commands
      uses: appleboy/ssh-action@v0.1.7
      timeout-minutes: 0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd proyecto/GDD-Maker/Backend
          if pgrep -x "node" > /dev/null; then     echo "Running"; else    npm run dev echo "Stopped"; fi
          echo "STARTING SERVER"
          echo "SERVER RUNNING"
          echo "APP DEPLOYED"     
    - name: Clean up
      uses: appleboy/ssh-action@v0.1.7
      timeout-minutes: 0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "STARTING SERVER"
          echo "SERVER RUNNING"
          echo "APP DEPLOYED" 
          
          
