name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executing SSH in remote instance
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd proyecto/GDD-Maker
          git pull
          cd Backend
          sudo npm i
          cd src
          if [ -d frontendBuild ]; then rm -r frontendBuild; fi
          cd ..
          cd ..
          cd Frontend
          sudo npm i
          ng build
          mv frontendBuild ../Backend/src/frontendBuild
          cd ../Backend/
          
          
          
