name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executing SSH in remote instance
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ls
          cd proyecto/GDD-Maker
          cd Backend
          npm i
          cd ..
          git pull
          
